# Generated by Django 4.0.5 on 2022-06-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_movingdetails_luggage_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='movingdetails',
            name='relocating_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
