# Generated by Django 4.0.5 on 2022-06-24 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('src', '0003_movingdetails_relocating_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movingdetails',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moving_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
