# Generated by Django 4.0.5 on 2022-06-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_rateus'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateus',
            name='reviews',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
